version: 2.1

jobs:
    install:
        working_directory: ~/repo
        docker:
            - image: circleci/python:3.6
        steps:
            - checkout
            - run: python -m virtualenv django-training.venv --python=python3
            - run: echo "source ./django-training.venv/bin/activate" > $BASH_ENV
            - restore_cache:
                key: deps-pip3-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - run: python -m pip install -r requirements.txt
            - save_cache:
                key: deps-pip3-{{ .Branch }}-{{ checksum "requirements.txt" }}
                paths:
                    - "django-training.venv"
    lint:
        working_directory: ~/repo
        docker:
            - image: circleci/python:3.6
        steps:
            - checkout
            - restore_cache:
                key: deps-pip3-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - run: echo "source ./django-training.venv/bin/activate" > $BASH_ENV
            - run: inv format

    test:
        working_directory: ~/repo
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run: echo "Full coverage or bust!"

workflows:
    version: 2
    build_test_lint:
        jobs:
            - install
            - lint:
                requires:
                    - install
            - test
